name: CI - Tests Python

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Descarregar el codi
        uses: actions/checkout@v4

      - name: Configurar Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instal·lar dependències
        run: |
          pip install pytest

      - name: Executar tests Unittest (tasques.py)
        run: |
          python -m unittest test_Unittest.py -v

      - name: Executar tests Pytest (tasca3.py)
        run: |
          pytest tasca3.py -v
